name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Replace Supabase credentials
        run: |
          # Reemplazar las variables de configuración en config.js
          sed -i "s|TU_SUPABASE_URL|${{ secrets.SUPABASE_URL }}|g" config.js
          sed -i "s|TU_SUPABASE_KEY|${{ secrets.SUPABASE_ANON_KEY }}|g" config.js
          
          # Verificar que los reemplazos se hicieron correctamente
          echo "Verificando configuración..."
          if grep -q "TU_SUPABASE_URL" config.js; then
            echo "⚠️ ADVERTENCIA: SUPABASE_URL no fue reemplazada"
            echo "Asegúrate de configurar el secret SUPABASE_URL en GitHub"
          else
            echo "✅ SUPABASE_URL configurada correctamente"
          fi
          
          if grep -q "TU_SUPABASE_KEY" config.js; then
            echo "⚠️ ADVERTENCIA: SUPABASE_ANON_KEY no fue reemplazada"
            echo "Asegúrate de configurar el secret SUPABASE_ANON_KEY en GitHub"
          else
            echo "✅ SUPABASE_ANON_KEY configurada correctamente"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

